name: mentore_app
description: "Mentore - Your multi-platform companion app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Network
  dio: ^5.8.0+1

  # Local Database
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  hive_flutter: ^1.1.0

  # Key-Value Storage
  shared_preferences: ^2.5.3

  # File System
  path_provider: ^2.1.6

  # UI & Animations
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  equatable: ^2.0.7
  logger: ^2.5.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0

  # Platform
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^2.5.8

  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
